export const AmazonAsinList = [
    {
        asin:"B01CJVVLUA",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/51dsI-aMgsL._SS125_.jpg",
        available:100,
        title:"Surf Excel Front Load",
        price: 314.00,
        actualprice: 450.00,
        asingroup:"detergent",
        type:"amazon",
        variationgroup: "SurfExcel",
        variation:"2 kg",
        externalBarcode: "int1"
    },
    {
        asin:"B01CJVVUY2",
        imageURL:"https://images-na.ssl-images-amazon.com/images/I/71PcniM-APL._AC_UL320_SR320,320_.jpg",
        available:100,
        title:"Surf Excel Front Load",
        price: 225.00,
        actualprice: 225.00,
        asingroup:"detergent",
        type:"amazon",
        variationgroup: "SurfExcel",
        variation:"1 kg",
        externalBarcode: "ext1"
    },
    {
        asin:"B01N5LENPM",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/513baVsqxfL._AC_UL246_SR190,246_FMwebp_QL70_.jpg",
        available:0,
        title:"Ariel Matic Top Load",
        price: 323.00,
        actualprice: 399.00,
        asingroup:"detergent",
        type:"amazon",
        variationgroup: "Ariel",
        variation:"2 kg",
        externalBarcode: "ext2"
    },
    {
        asin:"B07229HGVC",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/51WngspBz4L._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Ariel Matic Top Load",
        price: 853.00,
        actualprice: 898.00,
        asingroup:"detergent",
        type:"amazon",
        variationgroup: "Ariel",
        variation:"6 kg",
        externalBarcode: "ext3"
    },
    {
        asin:"B01CHUR9RM",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/41XJB2v3lGL._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Britannia Bourbon",
        price: 18.00,
        actualprice: 20.00,
        asingroup:"biscuit",
        type:"amazon",
        variationgroup: "bourbon",
        variation:"120 g",
        externalBarcode: "B00BFY2ERM"

    },
    {
        asin:"B01CHURRJM",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/416S-xou02L._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Britannia Good Day",
        price: 30.00,
        actualprice: 35.00,
        asingroup:"biscuit",
        type:"amazon",
        variationgroup: "goodday",
        variation:"200 g",
        externalBarcode: "ext4"
    },
    {
        asin:"B01M66ZABE",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/41GfcRfaQdL._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Britannia Good Day",
        price: 19.00,
        actualprice: 20.00,
        asingroup:"biscuit",
        type:"amazon",
        variationgroup: "goodday",
        variation:"100 g",
        externalBarcode: "ext5"
    },
    {
        asin:"B01CHUSV38",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/4145sK9RzJL._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Sunfeast Mom's Magic",
        price: 28.00,
        actualprice: 35.00,
        asingroup:"biscuit",
        type:"amazon",
        variationgroup: "mom",
        variation:"200 g",
        externalBarcode: "ext6"
    },
    {
        asin:"B01GCEGCP4",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/512AKf2zeFL._AC_UL587_SR453,587_FMwebp_QL65_.jpg",
        available:100,
        title:"Madhur Pure Sugar",
        price: 40.00,
        actualprice: 60.00,
        asingroup:"sugar",
        type:"amazon",
        variationgroup: "madhur",
        variation:"1 kg",
        externalBarcode: "ext7"
    },
    {
        asin:"B01GCF0XEY",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/51Kt7nFLqEL._AC_UL492_SR380,492_FMwebp_QL65_.jpg",
        available:100,
        title:"Madhur Pure Sugar",
        price: 195.00,
        actualprice: 295.00,
        asingroup:"sugar",
        type:"amazon",
        variationgroup: "madhur",
        variation:"5 kg",
        externalBarcode: "ext8"
    },
    {
        asin:"B01HBEUTGM",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/61421a+6uRL._AC_UL648_SR500,648_FMwebp_QL65_.jpg",
        available:100,
        title:"Kurkure Puffcorn",
        price: 19.00,
        actualprice: 20.00,
        asingroup:"chips",
        type:"amazon",
        variationgroup: "Kurkure",
        variation:"60 g",
        externalBarcode: "8901491366052"
    },
    {
        asin:"B01H5KWTH4",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/61jiAsaEHEL._AC_UL492_SR380,492_FMwebp_QL65_.jpg",
        available:100,
        title:"Little Hearts",
        price: 8.00,
        actualprice: 10.00,
        asingroup:"chips",
        type:"amazon",
        variationgroup: "Little",
        variation:"37 g",
        externalBarcode: "B01HBEUTGM"
    },
    {
        asin:"B01GCE8NJ2",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/51Jt6ZnV0dL._AC_UL547_SR422,547_FMwebp_QL65_.jpg",
        available:100,
        title:"Lite Chiwda",
        price: 25.00,
        actualprice: 25.00,
        asingroup:"chips",
        type:"amazon",
        variationgroup: "Lite",
        variation:"150 g",
        externalBarcode: "B01GCE8NJ2"
    },
    {
        asin:"B01CJUB700",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/51-rtI-TMbL._AC_UL492_SR380,492_FMwebp_QL65_.jpg",
        available:100,
        title:"Godrej Ezee",
        price: 84.00,
        actualprice: 90.00,
        asingroup:"detergent",
        type:"amazon",
        variationgroup: "Ezee",
        variation:"500 g",
        externalBarcode: "int5"
    },
    {
        asin:"B01GCFBG3G",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/61JoM2s1PvL._AC_UL492_SR380,492_FMwebp_QL65_.jpg",
        available:100,
        title:"Aashirvaad Superior",
        price: 400.00,
        actualprice: 344.00,
        asingroup:"atta",
        type:"amazon",
        variationgroup: "Aashirvaad",
        variation:"10 kg",
        externalBarcode: "int6"
    },
    {
        asin:"B01GCDVOTE",
        imageURL:"https://images-eu.ssl-images-amazon.com/images/I/61JoM2s1PvL._AC_UL492_SR380,492_FMwebp_QL65_.jpg",
        available:100,
        title:"Aashirvaad Superior",
        price: 206.00,
        actualprice: 235.00,
        asingroup:"atta",
        type:"amazon",
        variationgroup: "Aashirvaad",
        variation:"5 kg",
        externalBarcode: "int7"
    }
    
]
