export const CartItemList = [
    {
        cartItemId: 1,
        asin:"B01CJVVUY2",
        quantity:1,
        customerId:1,
        fromBarcode: "8901112",
        source:"Search",
        appliedOffer: "23453",
        externalPrice: 0.0,
    },
    {
        cartItemId: 2,
        asin:"B01M66ZABE",
        quantity:1,
        customerId:1,
        fromBarcode: "8901113",
        source:"Search",
        appliedOffer: "23454",
        externalPrice: 0.0,
    },
    {
        cartItemId: 3,
        asin:"B01GCF0XEY",
        quantity:1,
        customerId:2,
        fromBarcode: "8901114",
        source:"Search",
        appliedOffer: "23453",
        externalPrice: 0.0,
    },
]        