export const CartItemList = [
    {
        cartItemId: 1,
        asin:"B01CJVVLUA",
        quantity:1,
        customerId:1,
        fromBarcode: "int1",
        source:"Search",
        appliedOffer: "23453",
        externalPrice: 0.0,
    },
    {
        cartItemId: 2,
        asin:"B07229HGVC",
        quantity:1,
        customerId:1,
        fromBarcode: "int2",
        source:"Search",
        appliedOffer: "23454",
        externalPrice: 0.0,
    },
    {
        cartItemId: 3,
        asin:"B01N5LENPM",
        quantity:1,
        customerId:2,
        fromBarcode: "int3",
        source:"Search",
        appliedOffer: "23453",
        externalPrice: 0.0,
    },
]        